name: pokemon-fight-api-ci.

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check lint
        run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check test
        run: |
          npm ci
          npm run test
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check test
        run: |
          npm ci
          npm run build
